### ISSUE TITLE
Remove dependency for photo_controlloer.py

### ISSUE THREAD

**Issue by nsmohan** [nsmohan/PhotoNetwork#17]
Remove dependency for photo_controller.py and have server.py or client.py or any other applications start at startup or via a command.

**Comment by nmohan101** [comment]
pn_controller.c needs to do the following: 

1. start server.py or client.py based on client/server setting (photonetwork --start)
2. start event_handler.py if server.py is start
3. Kill all photonetwork process (photonetwork --stop)
